models/ShopEventOdd.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "shop_event_odd".
 *
 * @property integer $event_odd_id
 * @property integer $parent_match_id
 * @property integer $sub_type_id
 * @property string $max_bet
 * @property string $created
 * @property string $modified
 * @property string $odd_key
 * @property string $odd_value
 * @property string $odd_alias
 * @property string $special_bet_value
 * @property string $id_of_player
 * @property integer $status
 */
class ShopEventOdd extends \yii\db\ActiveRecord
{

    public $homeOdd;
    public $drawOdd;
    public $awayOdd;
    /**
     * @inheritdoc
     */


    public static function tableName()
    {
        return 'shop_event_odd';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_match_id', 'sub_type_id', 'max_bet', 'created', 'odd_key', 'odd_value', 'odd_alias', 'special_bet_value', 'id_of_player', 'status', 'homeOdd', 'drawOdd', 'awayOdd'], 'required'],
            [['parent_match_id', 'sub_type_id', 'status'], 'integer'],
            [['max_bet'], 'number'],
            [['created', 'modified'], 'safe'],
            [['odd_key'], 'string', 'max' => 200],
            [['odd_value', 'odd_alias', 'special_bet_value'], 'string', 'max' => 20],
            [['id_of_player'], 'string', 'max' => 30],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'event_odd_id' => 'Event Odd ID',
            'parent_match_id' => 'Parent Match ID',
            'sub_type_id' => 'Sub Type ID',
            'max_bet' => 'Max Bet',
            'created' => 'Created',
            'modified' => 'Modified',
            'odd_key' => 'Odds',
            'odd_value' => 'Odd Value',
            'odd_alias' => 'Odd Alias',
            'special_bet_value' => 'Special Bet Value',
            'id_of_player' => 'Id Of Player',
            'status' => 'Status',
        ];
    }

    public function match_to_add() {
        $data = array();
        $rows = (new \yii\db\Query())
                ->select(["CONCAT(parent_match_id, ' - ' ,home_team, ' - ', away_team) AS _match", 'parent_match_id'])
                ->from('match')
                ->where(['status'=>'1'])
                ->all();
        foreach ($rows as $key => $value) {
            $data[$value['parent_match_id']] = $value['_match'];
        }
        return $data;
    }

    public function addEventToShop($parent_match_id, $data) {
        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();
        try{
            // constants
            $sub_type_id = 10;
            $max_bet = 1;
            $created = date('Y-m-d H:i:s');
            $odd_alias = 'NULL';
            $special_bet_value = NULL;
            $id_of_player = 'NULL';
            $status = 0;

            // explode comma seperated odds
            $data1 = explode(',', $data);
            //print_r($data1);die();
            // get odd value for each odd_key
            $homeOddValue = $data1[0];
            $drawOddValue = $data1[1];
            $awayOddValue = $data1[2];

            $odds = array(
                "1" => $homeOddValue,
                "X" => $drawOddValue,
                "2" => $awayOddValue

            );
            
            foreach($odds as $key => $value){
                
                $sql = "INSERT INTO shop_event_odd(parent_match_id,sub_type_id,max_bet,odd_key,odd_value,odd_alias, special_bet_value, id_of_player, status, created) 
                        VALUES('$parent_match_id','$sub_type_id','$max_bet','$key','$value','$odd_alias','$special_bet_value','$id_of_player','$status','$created')

                ";

                $connection->createCommand($sql)->execute();
            }

            $transaction->commit();
            return TRUE;
        } catch (Exception $exc) {
            $transaction->rollback();
            return FALSE;
        }
        
    }


}

controllers/ShopEventOddController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\ShopEventOdd;
use app\models\ShopEventOddSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ShopEventOddController implements the CRUD actions for ShopEventOdd model.
 */
class ShopEventOddController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ShopEventOdd models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ShopEventOddSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ShopEventOdd model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ShopEventOdd model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ShopEventOdd();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->event_odd_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ShopEventOdd model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->event_odd_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ShopEventOdd model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ShopEventOdd model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ShopEventOdd the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ShopEventOdd::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAddeventtoshop() {
        $model = new ShopEventOdd();

        if(Yii::$app->request->post()) {

            $model->load(Yii::$app->request->post());
            
            $parent_match_id = $model->parent_match_id;

            $homeOdd = $model->homeOdd;
            $drawOdd = $model->drawOdd;
            $awayOdd = $model->awayOdd;

            $dataKey = $homeOdd.",".$drawOdd.",".$awayOdd;

            $data = rtrim($dataKey,' ');            
            
            $result = $model->addEventToShop($parent_match_id, $data);

            if($result) {
                $msg = "Event added to shop successfully.";
                $error = 'success';

                Yii::$app->getSession()->setFlash($error, $msg);

                return $this->redirect(['index']);

            } else {
                return $this->redirect('index');
            }
            

        } else {
        return $this->render('add_event_to_shop', [
                'model' => $model,
            ]);
        }
    }


}

views/shop-event-odd/_create_shop_event_odd_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\Match;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use kartik\depdrop\DepDrop;

/* @var $this yii\web\View */
/* @var $model app\models\Transaction */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="shop_event_odd-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'parent_match_id')->widget(Select2::classname(), [
        'data' => $model->match_to_add(),
        'language' => 'en',
        'class'=>'drop',
        'options' => ['placeholder' => 'Select a match ...', 'class'=>'drop', 'id'=>'drop', 'onchange'=>'$("#odds").show();'],
        'pluginOptions' => [
        'allowClear' => true
        ],
    ]); ?>
   
     
       
    <div class="row" id="odds" style="display: none;">
    	<div class="col-md-4">
    		<?= $form->field($model, 'homeOdd')->textArea(array('id'=>'homeOdd','placeholder'=>'1','readonly' => true)) ?>
    	</div>
    	<div class="col-md-4">
    		<?= $form->field($model, 'drawOdd')->textArea(array('placeholder'=>'X','readonly' => true)) ?>
    	</div>
    	<div class="col-md-4">
    		<?= $form->field($model, 'awayOdd')->textArea(array('placeholder'=>'2','readonly' => true)) ?>
    	</div>
    </div>

    <?= $form->field($model, 'created')->hiddenInput(['value' => date('Y-m-d H:i:s')])->label(false); ?>

    <?= $form->field($model, 'modified')->hiddenInput(['value' => date('Y-m-d H:i:s')])->label(false); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Submit' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary','data-toggle' => 'confirmation',]) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/shop-event-odd/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ShopEventOdd */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="shop-event-odd-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'parent_match_id')->textInput() ?>

    <?= $form->field($model, 'sub_type_id')->textInput() ?>

    <?= $form->field($model, 'max_bet')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created')->textInput() ?>

    <?= $form->field($model, 'modified')->textInput() ?>

    <?= $form->field($model, 'odd_key')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'odd_value')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'odd_alias')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'special_bet_value')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'id_of_player')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/shop-event-odd/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ShopEventOddSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="shop-event-odd-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'event_odd_id') ?>

    <?= $form->field($model, 'parent_match_id') ?>

    <?= $form->field($model, 'sub_type_id') ?>

    <?= $form->field($model, 'max_bet') ?>

    <?= $form->field($model, 'created') ?>

    <?php echo $form->field($model, 'modified') ?>

    <?php echo $form->field($model, 'odd_key') ?>

    <?php echo $form->field($model, 'odd_value') ?>

    <?php echo $form->field($model, 'odd_alias') ?>

    <?php echo $form->field($model, 'special_bet_value') ?>

    <?php echo $form->field($model, 'id_of_player') ?>

    <?php echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/shop-event-odd/add_event_to_shop.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\UserBetCancel */

$this->title = 'Shop Event Odds';
$this->params['breadcrumbs'][] = ['label' => 'Shop Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="shop_event_odd">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_create_shop_event_odd_form', [
        'model' => $model,
    ]) ?>

</div>
	

views/shop-event-odd/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\ShopEventOdd */

$this->title = 'Create Shop Event Odd';
$this->params['breadcrumbs'][] = ['label' => 'Shop Event Odds', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="shop-event-odd-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/shop-event-odd/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ShopEventOddSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Shop Event Odds';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="shop-event-odd-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
         <a class="btn btn-info" href="<?php echo Url::to(['shop-event-odd/addeventtoshop']) ?>">Add Events To Shop</a>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'event_odd_id',
            'parent_match_id',
            'sub_type_id',
            //'max_bet',
            'created',
            'modified',
            'odd_key',
            'odd_value',
            //'odd_alias',
            //'special_bet_value',
            //'id_of_player',
            'status',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/shop-event-odd/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ShopEventOdd */

$this->title = 'Update Shop Event Odd: ' . $model->event_odd_id;
$this->params['breadcrumbs'][] = ['label' => 'Shop Event Odds', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->event_odd_id, 'url' => ['view', 'id' => $model->event_odd_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="shop-event-odd-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/shop-event-odd/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ShopEventOdd */

$this->title = $model->event_odd_id;
$this->params['breadcrumbs'][] = ['label' => 'Shop Event Odds', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="shop-event-odd-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->event_odd_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->event_odd_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'event_odd_id',
            'parent_match_id',
            'sub_type_id',
            'max_bet',
            'created',
            'modified',
            'odd_key',
            'odd_value',
            'odd_alias',
            'special_bet_value',
            'id_of_player',
            'status',
        ],
    ]) ?>

</div>